PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE memes (id INTEGER PRIMARY KEY,nome text NOT NULL,link text NOT NULL,ranking INTEGER NULL);
INSERT INTO memes VALUES(1,'DJ André Marques manda AQUELE ao vivo','https://www.youtube.com/watch?v=zObCCCsCo2I',1);
INSERT INTO memes VALUES(2,'10 mandamentos rei do camarote','https://www.youtube.com/watch?v=atQvZ-nq0Go',5);
CREATE TABLE usuarios (id INTEGER PRIMARY KEY,nome text NOT NULL);
INSERT INTO usuarios VALUES(1,'henry');
CREATE TABLE usuarios_para_memes (id_meme INTEGER NOT NULL,id_usuario INTEGER NOT NULL,PRIMARY KEY(id_meme, id_usuario),FOREIGN KEY(id_meme) REFERENCES memes(id),FOREIGN KEY(id_usuario) REFERENCES usuarios(id));
INSERT INTO usuarios_para_memes VALUES(1,1);
INSERT INTO usuarios_para_memes VALUES(2,1);
COMMIT;
